default: &default
  adapter: postgresql
  database: "<%= ENV['POSTGRESQL_DATABASE'] %>"
  encoding: unicode
  host: "<%= ENV['POSTGRESQL_ADDRESS'] %>"
  password: "<%= ENV['POSTGRESQL_PASSWORD'] %>"
  pool: "<%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>"
  timeout: 5000
  username: "<%= ENV['POSTGRESQL_USERNAME'] %>"
  variables:
    statement_timeout: "<%= ENV.fetch('PG_STATEMENT_TIMEOUT') { 60000 } %>"

development:
  <<: *default
  database: noutube_db_development

test:
  <<: *default
  database: noutube_db_test

production:
  <<: *default
  database: noutube_db_production
